on:
  push:
    branches: main
  pull_request:
    branches: main

name: Render and deploy workshop

jobs:
  build:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-20.04, r: 'release'}
          - {os: windows-latest, r: 'release'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_DONTTEST_EXAMPLES_: false
      CRAN: ${{ matrix.config.cran }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2
          
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install packages 
        run: |-
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_deps()"
      
      - name: Build presentation
        run: |-
          Rscript -e "icons::download_fontawesome()"
          Rscript -e "rmarkdown::render('index.Rmd', 'all')"
                
      - name: Build data and script 
        run: |-
          Rscript -e "knitr::purl('index.Rmd', 'script.R')"
          Rscript -e "zip('data_and_script.zip', c('data', 'script.R'))"
        
      - name: Deploy workshop 
        if: matrix.config.os == 'ubuntu-20.04' && matrix.config.r == 'release'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
          exclude_assets: '.github,.gitignore,DESCRIPTION,makefile'
                
