name: deploy workshop

on:
  push:
    branches:
      - main

jobs:
  
  env: 
    GITHUB_PAT: ${{ secrets.PAT_R }}
  
  build:
    runs-on: ubuntu-latest
    container: rocker/verse:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        
      - name: Install apt-get packages
        run: |-
          sudo apt-get update
          sudo apt-get install -y pandoc rsync tree 
      
      - name: Install R packages 
        run: |
          Rscript -e "install.packages('remotes', repos = 'https://muug.ca/mirror/cran/')"
          Rscript -e "remotes::install_deps()"
      - name: Build presentation
        run: |
          icons::download_fontawesome()
          rmarkdown::render("index.Rmd", "all")
        shell: Rscript {0}
        
      - name: Build data and script 
        run: |
          knitr::purl("index.Rmd", "script.R")
          zip("data_and_script.zip", c("data", "script.R"))
        shell: Rscript {0}
                
      - name: Deploy workshop 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: .
          exclude_assets: '.github,.gitignore,DESCRIPTION,makefile'
